(venv) D:\Django\geekshop\geekshop>python manage.py shell
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from mainapp.models import ProductCategory

In [2]: new_cat = ProductCategory(name='Подарки')

In [3]: new_cat.save()

In [4]: from mainapp.models import Product

In [5]: new_prod = Product(name='Торт',category='Подарки')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-041414756843> in <module>
----> 1 new_prod = Product(name='Торт',category='Подарки')

D:\Django\venv\lib\site-packages\django\db\models\base.py in __init__(self, *args, **kwargs)
    483                 # checked) by the RelatedObjectDescriptor.
    484                 if rel_obj is not _DEFERRED:
--> 485                     _setattr(self, field.name, rel_obj)
    486             else:
    487                 if val is not _DEFERRED:

D:\Django\venv\lib\site-packages\django\db\models\fields\related_descriptors.py in __set__(self, instance, value)
    213         # An object must be an instance of the related class.
    214         if value is not None and not isinstance(value, self.field.remote_field.model._meta.concrete_model):
--> 215             raise ValueError(
    216                 'Cannot assign "%r": "%s.%s" must be a "%s" instance.' % (
    217                     value,

ValueError: Cannot assign "'Подарки'": "Product.category" must be a "ProductCategory" instance.

In [6]: new_prod = Product(name='Торт',category='Подарки')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-041414756843> in <module>
----> 1 new_prod = Product(name='Торт',category='Подарки')

D:\Django\venv\lib\site-packages\django\db\models\base.py in __init__(self, *args, **kwargs)
    483                 # checked) by the RelatedObjectDescriptor.
    484                 if rel_obj is not _DEFERRED:
--> 485                     _setattr(self, field.name, rel_obj)
    486             else:
    487                 if val is not _DEFERRED:

D:\Django\venv\lib\site-packages\django\db\models\fields\related_descriptors.py in __set__(self, instance, value)
    213         # An object must be an instance of the related class.
    214         if value is not None and not isinstance(value, self.field.remote_field.model._meta.concrete_model):
--> 215             raise ValueError(
    216                 'Cannot assign "%r": "%s.%s" must be a "%s" instance.' % (
    217                     value,

ValueError: Cannot assign "'Подарки'": "Product.category" must be a "ProductCategory" instance.

In [7]: new_prod = Product(name='Торт',category=new_cat)

In [8]: new_prod.save()

In [9]: print(Product.objects.all())
<QuerySet [<Product: Торт|Подарки>]>

In [10]:
